### ISSUE TITLE
Sample from README doesn't work

### ISSUE THREAD

**Issue by stiv-yakovenko** [timhuijgen/sockjs-wrap#2]
var Connection = require('sockjs-wrap');

gives an error:

Connection.start(sockjs_echo, {authentication: true});
           ^
TypeError: Connection.start is not a function

**Comment by timhuijgen** [comment]
The examples are probably out of date with the newest version.  I will update the examples tonight. I'll answer your other question too. 

Edit: I've updated the examples. The newest version works with un-initialised versions of the Connection. To make it working you have to make new Connection(). I did this so that you can extend the Connection with your own wrapper with es6 classes. I will make an example for that at a later point.
Edit 2: There is now a test script: `npm install` and `npm test` to run.
